apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: site-erpnext
  namespace: default
spec:
  interval: 15m
  path: "./site-deploy/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: erpnext
